---
driver:
  name: docker
  provision_command:
    # Modern chef includes ruby 2.3.1 which we're want to see
    - curl -L https://www.opscode.com/chef/install.sh | bash -s -- -v 12.14.89
    # For auto tests we need additional gems which requires build tools (example:)
    - apt-get -f -y install build-essential libxml2 libxml2-dev libxml2-utils

provisioner:
  name: chef_zero
  required_chef_omnibus: false
