---
driver:
  name: vagrant
  ssh:
    insert_key: false
  customize:
    cpus: 1
    memory: 1024

provisioner:
  name: chef_zero
  chef_client_path: /usr/bin/chef-client
  require_chef_omnibus: 12.14.89

transport:
  name: sftp

verifier:
  name: inspec
  format: doc

platforms:
  - name: centos-6.7
  - name: centos-7.2
    run_list:
      - recipe[yum]

  - name: debian-8.4
    run_list:
      - recipe[apt]

  - name: ubuntu-14.04
    run_list:
      - recipe[apt]

  - name: ubuntu-16.04
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[!{name}-test]
    attributes:

