source 'https://supermarket.chef.io'

metadata

group :integration do
  cookbook '!{name}-test', path: 'test/fixtures/cookbooks/!{name}-test'
  cookbook '!{name}-spec', path: 'test/fixtures/cookbooks/!{name}-spec'
end
