source 'https://rubygems.org'

gem 'chef', '~> 12.0'

group :lint do
  gem 'foodcritic', require: false
  gem 'rubocop', '>= 0.24', require: false
end

group :unit do
  gem 'berkshelf', '>= 3.1'
  gem 'chefspec', '>= 4.2.0'
  gem 'ci_reporter_rspec'
end

group :development do
  gem 'rake'
  gem 'stove'
  gem 'pry'
end

group :knife do
  gem 'knife-cookbook-doc'
  gem 'knife-supermarket'
  gem 'knife-solo_data_bag', '~> 1.0'
end

# Kitchen
group :kitchen do
  gem 'test-kitchen', '~> 1.3'
  gem 'kitchen-docker'
  gem 'kitchen-vagrant'
  gem 'kitchen-sync'
end

group :guard do
  gem 'guard', '>= 2.14'
  gem 'guard-bundler', require: false
  gem 'guard-rubocop', require: false
  gem 'guard-foodcritic', github: 'jsirex/guard-foodcritic', require: false
  gem 'guard-rspec', require: false
end
